#!/usr/bin/env python3
import argparse
import csv

fieldnames_in = [
        'buchungstag',
        'valuta',
        'auftraggeber',
        'empfänger',
        'konto',
        'iban',
        'blz',
        'bic',
        'vorgang',
        'kundenreferenz',
        'währung',
        'umsatz',
        'habensoll'
]
fieldnames_out = [
        'date',
        'payment',  # "Zahlung" in HomeBank
        'info',
        'payee',
        'memo',
        'amount',
        'category',
        'tags'
]

parser = argparse.ArgumentParser(description='convert voba cvs file for homebank')
parser.add_argument('voba_csv')
args = parser.parse_args()

with open(args.voba_csv, 'r', encoding='iso-8859-1') as csvfile, open('homebank.csv', 'w') as homebank_csvfile:
    reader = csv.DictReader(csvfile, fieldnames=fieldnames_in, delimiter=';', quotechar='"')
    writer = csv.DictWriter(homebank_csvfile, fieldnames=fieldnames_out, delimiter=';', quotechar='"')
    for row in reader:
        outrow = {
                'date':    row['buchungstag'].replace('.', '-'),
                'payment': 0,  # FIXME
                'info':    ' '.join(row['vorgang'].split('\n')) if row['vorgang'] is not None else '',
                'payee':   row['empfänger'],
                'amount':  '-' + row['umsatz'] if row['habensoll'] == 'S' else row['umsatz'],
        }
        writer.writerow(outrow)

