#!/usr/bin/env python3
import argparse
import csv

fieldnames_in = [
        'buchungstag',
        'valuta',
        'auftraggeber',
        'empfänger',
        'konto',
        'iban',
        'blz',
        'bic',
        'vorgang',
        'kundenreferenz',
        'währung',
        'umsatz',
        'habensoll'
]
fieldnames_out = [
        'date',
        'payment',  # "Zahlung" in HomeBank
        'info',
        'payee',
        'memo',
        'amount',
        'category',
        'tags'
]

parser = argparse.ArgumentParser(
        description='convert voba cvs file for homebank')
parser.add_argument('voba_csv')
args = parser.parse_args()

in_csv_filename = args.voba_csv
out_csv_filename = in_csv_filename.replace('.csv', '.homebank.csv')

with open(in_csv_filename, 'r', encoding='iso-8859-1') as csvfile, \
         open(out_csv_filename, 'w') as homebank_csvfile:
    reader = csv.DictReader(csvfile, fieldnames=fieldnames_in,
                            delimiter=';', quotechar='"')
    writer = csv.DictWriter(homebank_csvfile, fieldnames=fieldnames_out,
                            delimiter=';', quotechar='"')
    for row in reader:

        date = row['buchungstag'].replace('.', '-')
        if row['vorgang'] is not None:
            memo = ' '.join(row['vorgang'].split('\n'))
        else:
            memo = ''
        if row['habensoll'] == 'S':
            amount = '-' + row['umsatz']
        else:
            amount = row['umsatz']

        outrow = {
                'date':    date,
                'payment': 0,  # FIXME
                'memo':    memo,
                'payee':   row['empfänger'],
                'amount':  amount,
        }
        writer.writerow(outrow)
